### ISSUE TITLE
mkinitcpio-growrootfs doesn't understand UUID=foo

### ISSUE THREAD

**Issue by tycho** [GregSutcliffe/aur-projects#13]
On an EC2 instance:

```
:: running hook [growfs]
GrowRootFS: starting
GrowRootFS: FAILED: UUID=afa9b8e8-ece2-4fae-913a-0b6d438dfaa: does not exist
:: performing fsck on '/dev/xvda1'
```

/etc/fstab looks like:

```
#
# /etc/fstab: static file system information
#
# <file system> <dir>   <type>  <options>       <dump>  <pass>
UUID=afa9b8e8-ece2-4fae-913a-0b6d438dfaa1       /               ext4            rw,relatime,data=ordered        0 1
```

Looks like growpart doesn't know how to decode the UUID. Perhaps growfs-hook should resolve the UUID and pass the block device path to the growpart script.

**Comment by tycho** [comment]
Er, apparently the fstab isn't where it digests that from, it's the kernel command line. But it's the same content regardless:

```
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-linux-ec2 root=UUID=afa9b8e8-ece2-4fae-913a-0b6d438dfaa1 rw nomodeset console=ttyS0,9600n8 earlyprintk=serial,ttyS0,9600,verbose loglevel=7
```

**Comment by GregSutcliffe** [comment]
Sorry for the delay in getting back to you - thanks for the bug report. I'm using it on Openstack, so I have a fairly free hand in my root device specification. I'll see what I can do about fixing it up, but I'm kinda swamped right now - patches welcome if you've already figured it out :)

**Comment by tycho** [comment]
Hello!

This is the solution I came up with for UUID handling:
http://git.uplinklabs.net/snoonan/projects/archlinux/ec2/ec2-packages.git/commit/?id=3e8fdcaa2be41e719344b460017b00ccafe3fdc4

I'm still working on making this handle block devices with no partitions (e.g. whole block device is one big filesystem). It doesn't seem to understand disks with no partition tables, where the entire step could just be 'resize2fs'.

**Comment by GregSutcliffe** [comment]
Closing old issues - sorry I never fixed this.
